### ISSUE TITLE
Module 'eif' has no attribute

### ISSUE THREAD

**Issue by mlindsk** [ergodiclife/eif#1]
Hi,

I have installed the R version. I got the following 

> eif(as.matrix(mtcars), ntrees = 10L, sample_size = 5L, ExtensionLevel = 1L)
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'eif' has no attribute 'iForest'

> reticulate::py_module_available("eif")
[1] TRUE

> iso$iForest
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'eif' has no attribute 'iForest'
> 

On line 56 in `eif.R` you call `iso$iForest` which for some reason gives an error. I am not used to `reticulate` so I am kind of stuck investigating the error from here.

/Mads

**Comment by chris-park** [comment]
Hi @mlindsk, would you mind loading the `eif` and `reticulate` packages in your R session, then copy and paste the output of `sessionInfo()`?

**Comment by mlindsk** [comment]
Hi @ergodiclife 

Sure. Btw; the pure python seems to work fine. I ran [https://github.com/sahandha/eif/blob/master/Notebooks/EIF.ipynb](url) without problems.

Heres the output of the requested `sessionInfo()`:

```
library(eif)
library(reticulate)

eif(as.matrix(mtcars), ntrees = 10L, sample_size = 5L, ExtensionLevel = 1L)

Error in eif(as.matrix(mtcars), ntrees = 10L, sample_size = 5L, ExtensionLevel = 1L) : 
  Please install the 'eif' Python module by running py_install('eif') or equivalent.

sessionInfo()

R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.14 eif_0.0.1      

loaded via a namespace (and not attached):
[1] compiler_3.6.2 rappdirs_0.3.1 Rcpp_1.0.3     jsonlite_1.6.1
```

**Comment by chris-park** [comment]
Hi @mlindsk, I can't seem to reproduce your error. Do you use a `conda` or `virtualenv` by any chance? You might have to point `reticulate` to the correct environment (i.e. where you installed `eif`) using `reticulate::use_python()`, `reticulate::use_virtualenv()` or `reticulate::condaenv()`.

**Comment by mlindsk** [comment]
@ergodiclife thx for a quick response! Of course it was a matter of telling `reticulate` to use the correct version of python. I simply did the following (and put it in my `.Rprofile`):

```
my_py <- '/usr/bin/python3.6'
Sys.setenv(RETICULATE_PYTHON = my_py)
```

**Comment by mlindsk** [comment]
Sorry for closing the issue; i let it up to you if you have any further comments.

**Comment by chris-park** [comment]
Glad it worked out for you! Closing now.
